// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfFrQLdIa5c9eHZ6w3Kkuu_0SKWlfUP8',
    appId: '1:903421747903:web:934d6df106b7ae49c4dc0a',
    messagingSenderId: '903421747903',
    projectId: 'hotel-e69cc',
    authDomain: 'hotel-e69cc.firebaseapp.com',
    storageBucket: 'hotel-e69cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkcaYcyH94yZg9ofHkZVDGw0Wt-hVfvI',
    appId: '1:903421747903:android:863eee75e4ba532ac4dc0a',
    messagingSenderId: '903421747903',
    projectId: 'hotel-e69cc',
    storageBucket: 'hotel-e69cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0udmkXiXT6XY9oystSEXPLc9HngVlNQk',
    appId: '1:903421747903:ios:34ce65953de55af4c4dc0a',
    messagingSenderId: '903421747903',
    projectId: 'hotel-e69cc',
    storageBucket: 'hotel-e69cc.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0udmkXiXT6XY9oystSEXPLc9HngVlNQk',
    appId: '1:903421747903:ios:a02e6237b26c2098c4dc0a',
    messagingSenderId: '903421747903',
    projectId: 'hotel-e69cc',
    storageBucket: 'hotel-e69cc.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
